### ISSUE TITLE
Proper package name: wayland-virtwl-proxy or wayland-proxy-virtwl

### ISSUE THREAD

**Issue by sternenseemann** [talex5/wayland-proxy-virtwl#4]
The repo is called `wayland-virtwl-proxy`, but the dune and opam package within it are both called `wayland-proxy-virtwl`. Is this intentional? What is the “true” package name to be used by e. g. packaging?

**Comment by talex5** [comment]
`wayland-proxy-virtwl` is the correct name (I guess I should rename the repository).

I'm not sure it's really ready for packaging, though. It's just something I use on my computer. It works well enough for me, but no doubt other people would want other features, and I'm unlikely to have time to work on it much.

**Comment by sternenseemann** [comment]
I think it is at the very least interesting to have a version from git packaged for nixpkgs or spectrum's nixpkgs.

**Comment by talex5** [comment]
OK, that sounds reasonable. I've renamed the repository.
