### ISSUE TITLE
Socket activation

### ISSUE THREAD

**Issue by alyssais** [talex5/wayland-proxy-virtwl#54]
When running wayland-proxy-virtwl using a service manager, it would be useful to have some sort of readiness notification, so the service manager knows that other services that need to connect to wayland-proxy-virtwl can be started.  (In Spectrum's case, we'd run whatever application the VM is for at this point.)

For this sort of program, I think the best way to provide this functionality available would be to implement socket activation — let listening sockets be given as file descriptors inherited by the program.  That way, the service is ready as soon as the service manager has created those sockets, before the program is even started.  This should be pretty simple to implement, because the program just has to optionally skip a step (create, bind and listen on the sockets).  It also has the advantage that it's portable between service managers, unlike readiness notification, for which no standard interface exists.

Since wayland-proxy-virtwl can listen on multiple sockets (one for Wayland and one for X), I'd recommend the [`LISTEN_FDNAMES` interface](https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html#) originally from systemd, which is very easy to use from both systemd and s6 services.

**Comment by alyssais** [comment]
This would also partially solve #44, as the user could create and bind a socket however they wanted.

**Comment by talex5** [comment]
Good idea; I've been meaning to add that for a while.

**Comment by alyssais** [comment]
Fixed by https://github.com/talex5/wayland-proxy-virtwl/pull/83.
